### ISSUE TITLE
Planning for version 8.0 breaking changes

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/raven-java#335]
Punchlist of things that should be held off until a major release (I think?):

- [x] remove `@deprecated` stuff in the codebase #340
- [x] ~~move the `jul` `SentryHandler` to its own submodule~~
- [x] ~~move `slf4j` dep (40K) to logging submodules~~
- [x] ~~replace `jackson` (276K) with smaller (possibly shaded?) json dep~~
- [x] change `in_app` to a whitelist #49 & #344 
- [x] `RavenContext` rework -- as it will be a breaking change #345 
- [x] Add `app` to context (app version information, etc) #356 
- [x] Document Context / Breadcrumbs

Sentry PR for after 8.0: https://github.com/getsentry/sentry/pull/5163

**Comment by bretthoerner** [comment]
My Jackson size was incorrect, I was mistakenly counting jars that are only included in tests. 😭 

It looks like `slf4j` adds 40k and `jackson` adds 276k (for the latest versions). [moshi](https://github.com/square/moshi) is 119k, so a savings of 157k if we swap it out. Of course, if a user is already using `jackson` then it's "free" ... on the other hand that's true for `moshi` also...

Maybe it's best to not worry about these for now since they're a lot smaller than I expected.

For the record, `raven` is 127k and `raven-android` is 10k.
